// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $('button#refresh').click(function() {
      $('#compete h1').text('VS');
      $('section:first-of-type').removeClass().css("background-position", "0 0");
      $('section:nth-of-type(2)').removeClass().css({
        "background-position": "0 0",
        "-webkit-transform": "matrix(-1, 0, 0, 1, 0, 0)",
        "-moz-transform": "matrix(-1, 0, 0, 1, 0, 0)",
        "transform": "matrix(-1, 0, 0, 1, 0, 0)"
      });
      return $('span').removeClass();
    });
    return $('button#rock, button#paper, button#scissors').click(function() {
      var playerChoice;
      $('span#rock').addClass('start_1');
      $('span#paper').addClass('start_2');
      $('span#scissors').addClass('start_3');
      $("section:first-of-type").addClass('play_1');
      $("section:nth-of-type(2)").addClass('play_2');
      $('#compete h1').css({
        'z-index': 5,
        '-webkit-animation': "start_2 1s 3s ease-in",
        '-moz-animation': "start_2 1s 3s ease-in",
        "animation": "start_2 1s 3s ease-in"
      }).text('SHOOT!');
      playerChoice = $(this).attr('id');
      return setTimeout(function() {
        var computerChoice, game, tie, winner1, winner2;
        computerChoice = Math.floor(Math.random() * 3);
        computerChoice = (function() {
          switch (computerChoice) {
            case 0:
              return "rock";
            case 1:
              return "paper";
            case 2:
              return "scissors";
            default:
              return 'error';
          }
        })();
        if (computerChoice === "rock") {
          $('#compete section:nth-child(3)').css('background-position', '-400px 0');
        } else if (computerChoice === "paper") {
          $('#compete section:nth-child(3)').css('background-position', ' 0 -303px ');
        } else if (computerChoice === "scissors") {
          $('#compete section:nth-child(3)').css('background-position', '-402px -303px ');
        } else {
          alert('There seems to have been a error in my logic. Please try again.');
        }
        tie = function() {
          return $('#compete h1').text("IT'S A TIE!").css({
            "z-index": 5,
            "-webkit-animation": "results 2s ease-in-out",
            "-moz-animation": "results 2s ease-in-out",
            "animation": "results 2s ease-in-out"
          });
        };
        winner1 = function() {
          $('#compete section:first-child').addClass('winnerLeft');
          $('#compete section:nth-child(3)').addClass('loserRight');
          return $('#compete h1').text('PLAYER 1 WINS!').css({
            "z-index": 5,
            "-webkit-animation": "results 2s ease-in-out",
            "-moz-animation": "results 2s ease-in-out",
            "animation": "results 2s ease-in-out"
          });
        };
        winner2 = function() {
          $('#compete section:nth-child(3)').css({
            '-webkit-animation': 'winner_right 1.5s 2s forwards',
            '-moz-animation': 'winner_right 1.5s 2s forwards',
            'animation': 'winner_right 1.5s 2s forwards'
          });
          $('#compete section:first-child').addClass('loserLeft');
          return $('#compete h1').text('COMPUTER WINS!').css({
            "z-index": 5,
            "-webkit-animation": "results 2s ease-in-out",
            "-moz-animation": "results 2s ease-in-out",
            "animation": "results 2s ease-in-out"
          });
        };
        if (playerChoice === "rock") {
          $('#compete section:first-child').css('background-position', '-400px 0');
        } else if (playerChoice === "paper") {
          $('#compete section:first-child').css('background-position', '0 -303px ');
        } else if (playerChoice === 'scissors') {
          $('#compete section:first-child').css('background-position', '-402px -303px ');
        } else {
          alert('Oops! Looks there has been a mistake on my part. Please try again.');
        }
        game = function(choice1, choice2) {
          if (choice1 === 'rock') {
            if (choice2 === "scissors") {
              winner1();
            } else if (choice2 === "paper") {
              winner2();
            } else {
              tie();
            }
          }
          if (choice1 === 'paper') {
            if (choice2 === 'rock') {
              winner1();
            } else if (choice2 === "scissors") {
              winner2();
            } else {
              tie();
            }
          }
          if (choice1 === 'scissors') {
            if (choice2 === 'paper') {
              return winner1();
            } else if (choice2 === "rock") {
              return winner2();
            } else {
              return tie();
            }
          }
        };
        return game(playerChoice, computerChoice);
      }, 4000);
    });
  });

}).call(this);
